# Generated by Django 5.0.9 on 2024-11-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("elibrosLoja", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="enderecos",
            field=models.ManyToManyField(
                blank=True,
                related_name="enderecos_do_cliente",
                to="elibrosLoja.endereco",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
