# Generated by Django 5.0.3 on 2024-09-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('elibrosLoja', '0007_alter_pedido_numero_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='enderecos',
            field=models.ManyToManyField(related_name='enderecos_do_cliente', to='elibrosLoja.endereco'),
        ),
    ]
