# Generated by Django 5.1.3 on 2024-11-24 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
        ("elibrosLoja", "0003_alter_livro_data_de_adicao_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="enderecos",
        ),
        migrations.AddField(
            model_name="cliente",
            name="endereco",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="elibrosLoja.endereco",
            ),
        ),
    ]
