# Generated by Django 5.0.3 on 2024-09-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cliente_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dt_nasc',
            field=models.DateField(null=True),
        ),
    ]
