# Generated by Django 5.0.3 on 2024-09-02 19:26

import validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cliente_enderecos'),
        ('elibrosLoja', '0008_alter_pedido_numero_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='CPF',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dt_nasc',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='enderecos',
            field=models.ManyToManyField(blank=True, null=True, related_name='enderecos_do_cliente', to='elibrosLoja.endereco'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino'), ('NB', 'Não-binário'), ('PND', 'Prefiro não dizer'), ('OU', 'Outro')], default='F', max_length=20, null=True, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[validators.nao_nulo]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='outro_genero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Outro Gênero'),
        ),
    ]
