# Generated by Django 5.0.3 on 2024-09-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_cliente_cpf_alter_cliente_dt_nasc_and_more'),
        ('elibrosLoja', '0010_alter_pedido_numero_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='enderecos',
            field=models.ManyToManyField(blank=True, related_name='enderecos_do_cliente', to='elibrosLoja.endereco'),
        ),
    ]
