# Generated by Django 5.0.3 on 2024-09-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cliente_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino'), ('NB', 'Não-binário'), ('PND', 'Prefiro não dizer'), ('OU', 'Outro')], default='F', max_length=20, null=True, verbose_name='Identidade de gênero'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='outro_genero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Outro gênero'),
        ),
    ]
