# Generated by Django 5.0.9 on 2024-10-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_cliente_genero_alter_cliente_outro_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
