# Generated by Django 5.0.3 on 2024-09-02 16:58

import django.db.models.deletion
import validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.IntegerField()),
                ('uf', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=50)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GeneroTextual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True, validators=[validators.nao_nulo])),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, validators=[validators.verificar_vazio])),
                ('autor', models.CharField(max_length=150, validators=[validators.verificar_vazio])),
                ('data_de_publicacao', models.DateField(validators=[validators.nao_e_no_futuro])),
                ('capa', models.ImageField(upload_to='')),
                ('ISBN', models.CharField(max_length=15, unique=True, validators=[validators.verificar_vazio])),
                ('sinopse', models.TextField(validators=[validators.verificar_vazio])),
                ('editora', models.CharField(max_length=100, validators=[validators.verificar_vazio])),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5, validators=[validators.nao_negativo, validators.nao_nulo])),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('quantidade', models.IntegerField(validators=[validators.nao_negativo])),
                ('genero', models.ManyToManyField(related_name='Genero_do_Livro', to='elibrosLoja.generotextual')),
            ],
        ),
        migrations.CreateModel(
            name='GeneroLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generoTextual', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='elibrosLoja.generotextual')),
                ('livro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='elibrosLoja.livro')),
            ],
        ),
        migrations.CreateModel(
            name='LivroPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, validators=[validators.nao_negativo, validators.nao_nulo])),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livro_de_um_pedido', to='elibrosLoja.livro')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='nao_confirmado/processando', max_length=50, validators=[validators.nao_nulo])),
                ('data_de_pedido', models.DateTimeField(auto_now_add=True)),
                ('entrega_estimada', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_do_pedido', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
