# Generated by Django 5.0.9 on 2024-11-04 20:32

import datetime
import django.db.models.deletion
import validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cep", models.CharField(max_length=9)),
                ("uf", models.CharField(max_length=2)),
                ("cidade", models.CharField(max_length=30)),
                ("bairro", models.CharField(max_length=50)),
                ("rua", models.CharField(max_length=100)),
                ("numero", models.IntegerField()),
                ("complemento", models.CharField(blank=True, max_length=30, null=True)),
                ("identificacao", models.CharField(default="Endereço", max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="GeneroLiterario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="UploadImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="fotos_de_perfil/")),
            ],
        ),
        migrations.CreateModel(
            name="Carrinho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "total",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0.0, max_digits=5
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cliente_do_carrinho",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("subtitulo", models.CharField(blank=True, max_length=200, null=True)),
                ("autor", models.CharField(max_length=150)),
                (
                    "data_de_publicacao",
                    models.DateField(
                        blank=True, null=True, validators=[validators.nao_e_no_futuro]
                    ),
                ),
                (
                    "ano_de_publicacao",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            validators.nao_negativo,
                            validators.nao_nulo,
                            validators.nao_e_no_futuro,
                        ],
                    ),
                ),
                ("capa", models.ImageField(blank=True, null=True, upload_to="capas/")),
                ("ISBN", models.CharField(max_length=15, unique=True)),
                ("sinopse", models.TextField(blank=True, null=True)),
                ("editora", models.CharField(max_length=100)),
                (
                    "data_de_adicao",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 11, 4, 17, 32, 15, 936894)
                    ),
                ),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[validators.nao_negativo, validators.nao_nulo],
                    ),
                ),
                (
                    "desconto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "quantidade",
                    models.IntegerField(validators=[validators.nao_negativo]),
                ),
                (
                    "qtd_vendidos",
                    models.IntegerField(
                        default=0,
                        validators=[validators.nao_negativo],
                        verbose_name="Vendidos",
                    ),
                ),
                (
                    "categoria",
                    models.ManyToManyField(
                        blank=True,
                        related_name="Categoria_do_Livro",
                        to="elibrosLoja.categoria",
                    ),
                ),
                (
                    "genero_literario",
                    models.ManyToManyField(
                        blank=True,
                        related_name="Genero_Literario_do_Livro",
                        to="elibrosLoja.generoliterario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemCarrinho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField()),
                (
                    "preco",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5),
                ),
                (
                    "carrinho",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items_do_carrinho",
                        to="elibrosLoja.carrinho",
                    ),
                ),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="livro_selecionado",
                        to="elibrosLoja.livro",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "numero_pedido",
                    models.CharField(
                        default="006354734042",
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="nao_confirmado/processando",
                        max_length=50,
                        validators=[validators.nao_nulo],
                    ),
                ),
                ("data_de_pedido", models.DateTimeField(auto_now_add=True)),
                ("entrega_estimada", models.DateTimeField()),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cliente_do_pedido",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "itens",
                    models.ManyToManyField(
                        related_name="itens_do_pedido", to="elibrosLoja.itemcarrinho"
                    ),
                ),
            ],
        ),
    ]
