# Generated by Django 5.1.3 on 2024-11-14 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrosLoja", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="data_de_adicao",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 14, 15, 43, 57, 8593)
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="numero_pedido",
            field=models.CharField(
                default="084779533912", max_length=12, primary_key=True, serialize=False
            ),
        ),
    ]
