# Generated by Django 5.0.3 on 2024-09-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrosLoja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='id',
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(default='253634930483', max_length=12, primary_key=True, serialize=False),
        ),
    ]
