# Generated by Django 5.0.3 on 2024-09-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrosLoja', '0002_alter_carrinho_items_alter_pedido_numero_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrinho',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='carrinho',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, related_name='items_do_carrinho', to='elibrosLoja.itemcarrinho'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(default='004676646015', max_length=12, primary_key=True, serialize=False),
        ),
    ]
