# Generated by Django 5.0.3 on 2024-09-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrosLoja', '0002_remove_pedido_id_pedido_numero_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='livros_do_pedido',
            field=models.ManyToManyField(related_name='livro_do_pedido', to='elibrosLoja.livropedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(default='614397065960', max_length=12, primary_key=True, serialize=False),
        ),
    ]
