# Generated by Django 5.0.3 on 2024-09-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrosLoja', '0003_itemcarrinho_slug_alter_carrinho_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrinho',
            name='slug',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(default='986860811027', max_length=12, primary_key=True, serialize=False),
        ),
    ]
