# Generated by Django 5.1.3 on 2024-11-24 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrosLoja", "0004_alter_livro_data_de_adicao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="data_de_adicao",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 24, 20, 14, 37, 235853)
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="numero_pedido",
            field=models.CharField(
                default="592673053493", max_length=12, primary_key=True, serialize=False
            ),
        ),
    ]
