# Generated by Django 5.0.3 on 2024-09-02 18:39

import validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrosLoja', '0004_livro_ano_de_publicacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='ano_de_publicacao',
            field=models.IntegerField(blank=True, null=True, validators=[validators.nao_negativo, validators.nao_nulo]),
        ),
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas/'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_de_publicacao',
            field=models.DateField(blank=True, null=True, validators=[validators.nao_e_no_futuro]),
        ),
        migrations.AlterField(
            model_name='livro',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(default='486436885413', max_length=12, primary_key=True, serialize=False),
        ),
    ]
