# Generated by Django 5.1.3 on 2024-11-24 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrosLoja", "0005_alter_livro_data_de_adicao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Desconto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=3)),
                ("ativo", models.BooleanField(default=True)),
                ("data_inicio", models.DateTimeField()),
                ("data_fim", models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name="livro",
            name="data_de_adicao",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 24, 20, 14, 57, 839395)
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="numero_pedido",
            field=models.CharField(
                default="020892648038", max_length=12, primary_key=True, serialize=False
            ),
        ),
    ]
