# Generated by Django 5.0.3 on 2024-09-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrosLoja', '0005_alter_itemcarrinho_preço_alter_pedido_numero_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(default='323421187551', max_length=12, primary_key=True, serialize=False),
        ),
    ]
