# Generated by Django 5.1.3 on 2024-11-24 23:20

import datetime
import validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrosLoja", "0006_desconto_alter_livro_data_de_adicao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="valor_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                validators=[validators.nao_negativo, validators.nao_nulo],
            ),
        ),
        migrations.AlterField(
            model_name="livro",
            name="data_de_adicao",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 11, 24, 20, 20, 43, 608582)
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="numero_pedido",
            field=models.CharField(
                default="013844705788", max_length=12, primary_key=True, serialize=False
            ),
        ),
    ]
