# Generated by Django 5.0.9 on 2024-09-14 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrosLoja', '0007_remove_pedido_carrinho_carrinho_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='items_do_carrinho', to='elibrosLoja.itemcarrinho'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_de_adicao',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 19, 1, 28, 365703)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(default='493211617459', max_length=12, primary_key=True, serialize=False),
        ),
    ]
