# Generated by Django 5.0.9 on 2024-09-14 23:04

import datetime
import validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrosLoja', '0009_categoria_alter_livro_data_de_adicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='data_de_adicao',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 20, 4, 33, 130566)),
        ),
        migrations.AlterField(
            model_name='livro',
            name='qtd_vendidos',
            field=models.IntegerField(default=0, validators=[validators.nao_negativo], verbose_name='Vendidos'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(default='006350951206', max_length=12, primary_key=True, serialize=False),
        ),
    ]
