# Generated by Django 5.0.9 on 2024-09-14 23:52

import datetime
import validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrosLoja', '0010_alter_livro_data_de_adicao_alter_livro_qtd_vendidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='ISBN',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='ano_de_publicacao',
            field=models.IntegerField(blank=True, null=True, validators=[validators.nao_negativo, validators.nao_nulo, validators.nao_e_no_futuro]),
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='livro',
            name='categoria',
            field=models.ManyToManyField(blank=True, null=True, related_name='Categoria_do_Livro', to='elibrosLoja.categoria'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_de_adicao',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 20, 52, 37, 152834)),
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='livro',
            name='sinopse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(default='071582279129', max_length=12, primary_key=True, serialize=False),
        ),
    ]
