# Generated by Django 5.0.9 on 2024-09-15 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrosLoja', '0011_alter_livro_isbn_alter_livro_ano_de_publicacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneroLiterario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_de_adicao',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 15, 15, 35, 48, 1327)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(default='421561264065', max_length=12, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='GeneroLivro',
        ),
    ]
