# Generated by Django 5.0.9 on 2024-09-15 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrosLoja', '0012_generoliterario_alter_livro_data_de_adicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='genero_literario',
            field=models.ManyToManyField(blank=True, null=True, related_name='Genero_Literario_do_Livro', to='elibrosLoja.generoliterario'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_de_adicao',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 15, 15, 40, 59, 348802)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(default='751826434195', max_length=12, primary_key=True, serialize=False),
        ),
    ]
