# Generated by Django 5.0.9 on 2024-09-15 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrosLoja', '0013_livro_genero_literario_alter_livro_data_de_adicao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcarrinho',
            old_name='preço',
            new_name='preco',
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_de_adicao',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 15, 20, 59, 37, 13009)),
        ),
        migrations.AlterField(
            model_name='livro',
            name='genero',
            field=models.ManyToManyField(blank=True, null=True, related_name='Genero_Textual_do_Livro', to='elibrosLoja.generotextual'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(default='307787794400', max_length=12, primary_key=True, serialize=False),
        ),
    ]
