# Generated by Django 5.0.9 on 2024-09-16 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrosLoja', '0014_rename_preço_itemcarrinho_preco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='categoria',
            field=models.ManyToManyField(blank=True, related_name='Categoria_do_Livro', to='elibrosLoja.categoria'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_de_adicao',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 8, 17, 39, 992838)),
        ),
        migrations.AlterField(
            model_name='livro',
            name='genero',
            field=models.ManyToManyField(blank=True, related_name='Genero_Textual_do_Livro', to='elibrosLoja.generotextual'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='genero_literario',
            field=models.ManyToManyField(blank=True, related_name='Genero_Literario_do_Livro', to='elibrosLoja.generoliterario'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(default='060076900164', max_length=12, primary_key=True, serialize=False),
        ),
    ]
