# Generated by Django 5.0.9 on 2024-10-05 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrosLoja', '0017_endereco_identificacao_alter_livro_data_de_adicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_de_adicao',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 5, 19, 24, 58, 225492)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(default='233546889084', max_length=12, primary_key=True, serialize=False),
        ),
    ]
