# Generated by Django 5.0.3 on 2024-10-21 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrosLoja', '0019_alter_carrinho_cliente_alter_livro_data_de_adicao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='genero',
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_de_adicao',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 21, 13, 51, 13, 305314)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(default='840314636113', max_length=12, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='GeneroTextual',
        ),
    ]
