# Generated by Django 5.0.3 on 2024-10-21 17:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrosLoja', '0020_remove_livro_genero_alter_livro_data_de_adicao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='items',
        ),
        migrations.AddField(
            model_name='itemcarrinho',
            name='carrinho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrinho', to='elibrosLoja.carrinho'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_de_adicao',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 21, 14, 17, 20, 289810)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(default='797871622303', max_length=12, primary_key=True, serialize=False),
        ),
    ]
